# TODO: try to change to alpine image
FROM python:3.8.6-alpine

# Docker Files Vars
ARG LISTEN_PORT=8000 
ARG LISTEN_IP="0.0.0.0"

# Default values for deploying with multiomix image
ENV LISTEN_PORT $LISTEN_PORT
ENV LISTEN_IP $LISTEN_IP
ENV DJANGO_SETTINGS_MODULE "multiomics_intermediate.settings_prod"
ENV RESULT_DATAFRAME_LIMIT_ROWS 500
ENV TABLE_PAGE_SIZE 10

# Modulector connection parameters
ENV MODULECTOR_HOST "127.0.0.1"
ENV MODULECTOR_PORT "8001"

# BioAPI connection parameters
ENV BIOAPI_HOST "127.0.0.1"
ENV BIOAPI_PORT "8002"

# PostgreSQL DB connection parameters
ENV POSTGRES_USERNAME "multiomics"
ENV POSTGRES_PASSWORD "multiomics"
ENV POSTGRES_HOST "db"
ENV POSTGRES_PORT 5432
ENV POSTGRES_DB "multiomics"
    
# Mongo DB connection parameters
ENV MONGO_USERNAME "multiomics"
ENV MONGO_PASSWORD "multiomics"
ENV MONGO_HOST "mongo"
ENV MONGO_PORT 27017
ENV MONGO_DB "multiomics"

# Redis
ENV REDIS_HOST "redis"
ENV REDIS_PORT 6379

# Installs system dependencies
RUN apk add curl libressl libxml2 gsl \
    && mkdir /config \
    && mkdir /src

# Installs Python dependencies
# TODO: make a custom requirements.txt for celery workers' image. They don't need Daphne or Flower for example
ADD config/requirements_celery.txt /config/requirements.txt
WORKDIR /src
ADD src .
RUN pip install --upgrade pip && pip3 install -r /config/requirements.txt

ENTRYPOINT ["/bin/bash", "-c", "/src/entrypoint_celery.sh"]
