# Complete the SECRET_KEY with the output of `get_random_secret_key()` from Django
x-common-variables: &common-variables
    SECRET_KEY: ''  # <- Set this to the output of `get_random_secret_key()` from Django

services:
    # PostgreSQL
    db:
        image: postgres:16
        restart: 'always'
        command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
        environment:
            <<: *common-variables
            # IMPORTANT: these must match the credentials below in the 'multiomix' service
            POSTGRES_USER: 'multiomics'
            POSTGRES_PASSWORD: 'multiomics'
            POSTGRES_DB: 'multiomics'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./config/postgres/postgres.conf:/etc/postgresql/postgresql.conf
        deploy:
            endpoint_mode: dnsrr

    # MongoDB Server
    mongo:
        image: mongo:4.2
        restart: 'always'
        environment:
            # IMPORTANT: these must match credentials in the 'multiomix' service
            MONGO_INITDB_ROOT_USERNAME: 'multiomics'
            MONGO_INITDB_ROOT_PASSWORD: 'multiomics'
            MONGO_INITDB_DATABASE: 'multiomics'
        command: --config /etc/mongo/mongod.conf
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb
            - ./config/mongo/mongod.conf:/etc/mongo/mongod.conf

    # Redis Server for Websockets
    redis:
        image: redis:6.2.14-alpine
        restart: 'always'
        volumes:
            - redis_data:/data

    # Django Proxy (NGINX)
    nginx:
        image: nginx:1.27
        restart: 'always'
        ports:
            - '80:8000'
            # - '443:443' # Uncomment for HTTPS support
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ./config/nginx/certificates:/etc/nginx/certificates
            - static_data:/static
            - media_data:/media
        depends_on:
            - multiomix

    # Celery worker for emailing
    emailing-celery-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - redis
        volumes:
            - media_data:/src/media
            - static_data:/src/static
        environment:
            <<: *common-variables
            # Common variables including the needed SECRET_KEY for production
            # Celery parameters
            QUEUE_NAME: 'emailing'
            CONCURRENCY: 1

    # Celery worker for correlation analysis
    correlation-analysis-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'correlation_analysis'
            CONCURRENCY: 2

    # Celery worker for feature selection
    fs-experiments-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'feature_selection'
            CONCURRENCY: 2

    # Celery worker for statistical validation
    stats-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'stats'
            CONCURRENCY: 2

    # Celery worker for inference
    inference-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'inference'
            CONCURRENCY: 2

    # Celery worker for syncing datasets
    sync-datasets-worker:
        image: omicsdatascience/multiomix:5.5.0-celery
        restart: 'always'
        depends_on:
            - db
            - mongo
        volumes:
            - media_data:/src/media
        environment:
            # Celery parameters
            QUEUE_NAME: 'sync_datasets'
            CONCURRENCY: 1  # NOTE: concurrency is set to minimum by default for this service

    # Django backend service
    multiomix:
        image: omicsdatascience/multiomix:5.5.0
        restart: 'always'
        environment:
            <<: *common-variables
            # Common variables including the needed SECRET_KEY for production
            DJANGO_SETTINGS_MODULE: 'rwe.settings_prod'
            ENABLE_SECURITY: 'false'
        volumes:
            - static_data:/src/static
            - media_data:/src/media
            - logs_data:/logs
        depends_on:
            - db
            - mongo
            - correlation-analysis-worker
            - fs-experiments-worker
            - stats-worker
            - inference-worker
            - sync-datasets-worker

volumes:
    mongo_data:
        external: true
        name: 'multiomics_intermediate_mongo_data'
    mongo_config:
        external: true
        name: 'multiomics_intermediate_mongo_config'
    postgres_data:
        external: true
        name: 'multiomics_intermediate_postgres_data'
    redis_data:
        external: true
        name: 'multiomics_intermediate_redis_data'
    static_data:
        external: true
        name: 'multiomics_intermediate_static_data'
    media_data:
        external: true
        name: 'multiomics_intermediate_media_data'
    logs_data:
        external: true
        name: 'multiomics_intermediate_logs_data'
