sonar.projectKey=omics-datascience_multiomix
sonar.organization=omics-datascience
sonar.projectName=multiomix
sonar.projectVersion=1.0

# Sources - scan everything in src/
sonar.sources=src

# Exclude only node_modules, migrations and build artifacts
sonar.exclusions=**/node_modules/**,**/migrations/**,**/__pycache__/**,**/venv/**,**/.venv/**,**/htmlcov/**,**/staticfiles/**,**/*.pyc,**/email/**,**/dist/**

# Python settings
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript settings
sonar.javascript.node.maxspace=4096
