# Generated by Django 3.0.3 on 2020-05-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='description',
            new_name='location',
        ),
    ]
