# Generated by Django 4.2.15 on 2025-04-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20220923_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='institutionadministration',
            options={'ordering': ['-id']},
        ),
    ]
