# Generated by Django 3.2.13 on 2023-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0004_auto_20230216_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='origin',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Intersection'), (3, 'Feature Selection'), (4, 'Differential Expression')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biomarker',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Failed'), (3, 'Processing')], default=1),
            preserve_default=False,
        ),
    ]
