# Generated by Django 3.2.13 on 2023-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0008_statisticalvalidation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalvalidation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticalvalidation',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
