# Generated by Django 3.2.13 on 2023-04-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0011_auto_20230425_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticalvalidationsourceresult',
            name='source',
        ),
        migrations.DeleteModel(
            name='StatisticalValidation',
        ),
        migrations.DeleteModel(
            name='StatisticalValidationSourceResult',
        ),
    ]
