# Generated by Django 3.2.13 on 2023-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0015_alter_biomarker_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
