# Generated by Django 4.2.15 on 2024-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0018_alter_biomarker_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
