# Generated by Django 4.2.15 on 2024-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20220923_2322'),
        ('biomarkers', '0019_biomarker_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='shared_institutions',
            field=models.ManyToManyField(blank=True, related_name='biomarkers', to='institutions.institution'),
        ),
    ]
