# Generated by Django 4.2.15 on 2025-04-10 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0005_alter_institution_options_and_more'),
        ('biomarkers', '0020_biomarker_shared_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_biomarkers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='shared_institutions',
            field=models.ManyToManyField(blank=True, related_name='shared_biomarkers', to='institutions.institution'),
        ),
    ]
