# Generated by Django 4.2.15 on 2025-04-25 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomarkers', '0021_biomarker_shared_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_users_biomarkers', to=settings.AUTH_USER_MODEL),
        ),
    ]
