# Generated by Django 4.2.19 on 2026-06-23 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tissues", "0002_tissue_code_and_initial_data"),
        ("biomarkers", "0022_alter_biomarker_shared_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="biomarker",
            name="tissues",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tissues.tissue",
            ),
        ),
    ]
