# Generated by Django 4.2.19 on 2025-08-03 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0005_alter_institution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_service', '0061_alter_experiment_shared_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentialExpressionExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('clinical_attribute', models.CharField(max_length=100)),
                ('threshold_percentile', models.FloatField(default=0.15)),
                ('threshold', models.FloatField(default=0.0001)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('clinical_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_expression_as_clinical', to='api_service.experimentclinicalsource')),
                ('mrna_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_expression_as_mrna', to='api_service.experimentsource')),
                ('shared_institutions', models.ManyToManyField(blank=True, related_name='shared_differential_expression', to='institutions.institution')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_users_differential_expression', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
