# Generated by Django 4.2.19 on 2026-01-29 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0005_alter_institution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_service', '0062_alter_experiment_clinical_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentialExpressionExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('clinical_attribute', models.CharField(max_length=100)),
                ('tool', models.CharField(choices=[('DESEQ', 'Deseq'), ('LIMMA', 'Limma')], default='DESEQ', help_text='Tool to use for differential expression analysis', max_length=10)),
                ('threshold_percentile', models.FloatField(default=0.15)),
                ('threshold', models.FloatField(default=0.0001)),
                ('top', models.IntegerField(default=100, help_text='Number of significant results to keep (max 1000)')),
                ('execution_time', models.FloatField(blank=True, default=0.0, help_text='Execution time in seconds', null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery Task ID', max_length=100, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0, help_text='Number of attempts to prevent a buggy experiment running forever')),
                ('state', models.IntegerField(choices=[(1, 'Completed'), (2, 'Finished With Error'), (3, 'In Process'), (4, 'Waiting For Queue'), (5, 'No Samples In Common'), (6, 'Stopping'), (7, 'Stopped'), (8, 'Reached Attempts Limit'), (9, 'No Features Found'), (10, 'Empty Dataset'), (11, 'Timeout Exceeded')], default=4, help_text='Current state of the differential expression experiment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the experiment was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the experiment was last updated')),
                ('is_public', models.BooleanField(default=False)),
                ('clinical_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_expression_experiments_as_clinical', to='api_service.experimentclinicalsource')),
                ('mrna_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differential_expression_experiments_as_mrna', to='api_service.experimentsource')),
                ('shared_institutions', models.ManyToManyField(blank=True, related_name='shared_differential_expression', to='institutions.institution')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_users_differential_expression', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentialExpressionExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(help_text='Gene identifier', max_length=100)),
                ('ave_expr', models.FloatField(help_text='Average expression level')),
                ('p_value', models.FloatField(help_text='P-value from statistical test')),
                ('adj_p_val', models.FloatField(help_text='Adjusted P-value (FDR corrected)')),
                ('log_fc', models.FloatField(help_text='Log fold change')),
                ('t_statistic', models.FloatField(help_text='t-statistic from the test')),
                ('b_statistic', models.FloatField(help_text='B-statistic (log-odds of differential expression)')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='differential_expression.differentialexpressionexperiment')),
            ],
            options={
                'indexes': [models.Index(fields=['experiment', 'adj_p_val'], name='differentia_experim_c0aff3_idx'), models.Index(fields=['experiment', 'log_fc'], name='differentia_experim_084601_idx'), models.Index(fields=['gene'], name='differentia_gene_7c8c66_idx')],
                'unique_together': {('experiment', 'gene')},
            },
        ),
    ]
