# Generated by Django 4.2.19 on 2025-08-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("differential_expression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="attempt",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of attempts to prevent a buggy experiment running forever",
            ),
        ),
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="execution_time",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Execution time in seconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Completed"),
                    (2, "Finished With Error"),
                    (3, "In Process"),
                    (4, "Waiting For Queue"),
                    (5, "No Samples In Common"),
                    (6, "Stopping"),
                    (7, "Stopped"),
                    (8, "Reached Attempts Limit"),
                    (9, "No Features Found"),
                    (10, "Empty Dataset"),
                    (11, "Timeout Exceeded"),
                ],
                default=4,
                help_text="State of the differential expression experiment",
            ),
        ),
        migrations.AlterField(
            model_name="differentialexpressionexperiment",
            name="task_id",
            field=models.CharField(
                blank=True, help_text="Celery Task ID", max_length=100, null=True
            ),
        ),
    ]
