# Generated by Django 4.2.19 on 2025-08-09 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("differential_expression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When the experiment was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the experiment was last updated"
            ),
        ),
    ]
