# Generated by Django 4.2.19 on 2025-08-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "differential_expression",
            "0002_differentialexpressionexperiment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="top",
            field=models.IntegerField(
                default=100,
                help_text="Number of significant results to keep (max 1000)",
            ),
        ),
        migrations.AlterField(
            model_name="differentialexpressionexperiment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the experiment was created",
                null=True,
            ),
        ),
    ]
