# Generated by Django 4.2.19 on 2025-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "differential_expression",
            "0002_differentialexpressionexperiment_attempt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="differentialexpressionexperiment",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Completed"),
                    (2, "Finished With Error"),
                    (3, "In Process"),
                    (4, "Waiting For Queue"),
                    (5, "No Samples In Common"),
                    (6, "Stopping"),
                    (7, "Stopped"),
                    (8, "Reached Attempts Limit"),
                    (9, "No Features Found"),
                    (10, "Empty Dataset"),
                    (11, "Timeout Exceeded"),
                ],
                default=4,
                help_text="Current state of the differential expression experiment",
            ),
        ),
    ]
