# Generated by Django 4.2.19 on 2026-07-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("differential_expression", "0002_differentialexpressionexperiment_tissues"),
    ]

    operations = [
        migrations.RenameField(
            model_name="differentialexpressionexperiment",
            old_name="tissues",
            new_name="tissue",
        ),
    ]
