# Generated by Django 4.2.19 on 2025-10-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "differential_expression",
            "0003_differentialexpressionexperiment_top_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="differentialexpressionexperiment",
            name="tool",
            field=models.CharField(
                choices=[("DESEQ", "Deseq"), ("LIMMA", "Limma")],
                default="DESEQ",
                help_text="Tool to use for differential expression analysis",
                max_length=10,
            ),
        ),
    ]
