# Generated by Django 4.2.19 on 2026-02-26 22:58

from django.db import migrations

TISSUES = [
    'Cerebro (GBM)',
    'Cerebro (Glioma)',
    'Colon',
    'Cérvix',
    'Estómago',
    'Esófago',
    'Glándula Adrenal',
    'Hígado',
    'Mama',
    'Ovario',
    'Piel',
    'Próstata',
    'Pulmón',
    'Pulmón (Escamoso)',
    'Páncreas',
    'Recto',
    'Riñón (KIRC)',
    'Riñón (KIRP)',
    'Sangre (Leucemia)',
    'Testículo',
    'Tiroides',
    'Vejiga',
    'Útero',
]


def load_tissues(apps, schema_editor):
    Tissue = apps.get_model('tissues', 'Tissue')
    Tissue.objects.bulk_create([Tissue(name=name) for name in TISSUES])


def unload_tissues(apps, schema_editor):
    Tissue = apps.get_model('tissues', 'Tissue')
    Tissue.objects.filter(name__in=TISSUES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tissues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_tissues, reverse_code=unload_tissues),
    ]