import { GraphEdge, GraphNode } from './types'

export const MOCK_NODES: GraphNode[] = [
    { id: 'gene_braf', label: 'BRAF', type: 'Gene', size: 66 },
    { id: 'gene_mek1', label: 'MEK1', type: 'Gene', size: 46 },
    { id: 'gene_mek2', label: 'MEK2', type: 'Gene', size: 44 },
    { id: 'gene_erk1', label: 'ERK1', type: 'Gene', size: 42 },
    { id: 'gene_erk2', label: 'ERK2', type: 'Gene', size: 42 },
    { id: 'gene_myc', label: 'MYC', type: 'Gene', size: 38 },
    { id: 'gene_fos', label: 'FOS', type: 'Gene', size: 36 },
    { id: 'gene_ccnd1', label: 'CCND1', type: 'Gene', size: 36 },
    { id: 'gene_elk1', label: 'ELK1', type: 'Gene', size: 34 },
    { id: 'gene_dusp6', label: 'DUSP6', type: 'Gene', size: 34 },
    { id: 'gene_spry2', label: 'SPRY2', type: 'Gene', size: 32 },
    { id: 'gene_map3k8', label: 'MAP3K8', type: 'Gene', size: 32 },
    { id: 'mir_17', label: 'miR-17', type: 'miRNA', size: 28 },
    { id: 'mir_21', label: 'miR-21', type: 'miRNA', size: 28 },
    { id: 'cna_7q34', label: '7q34 gain', type: 'CNA', size: 34 },
    { id: 'meth_rassf1', label: 'RASSF1 meth', type: 'Methylation', size: 34 },
    { id: 'drug_vemurafenib', label: 'Vemurafenib', type: 'Drug', size: 36 },
    { id: 'gene_akt1', label: 'AKT1', type: 'Gene', size: 32 },
    { id: 'gene_grb2', label: 'GRB2', type: 'Gene', size: 30 },
    { id: 'gene_raf1', label: 'RAF1', type: 'Gene', size: 32 },
    { id: 'drug_trametinib', label: 'Trametinib', type: 'Drug', size: 34 },
    { id: 'gene_mapkapk2', label: 'MAPKAPK2', type: 'Gene', size: 30 },
    { id: 'gene_rps6ka1', label: 'RPS6KA1', type: 'Gene', size: 30 },
    { id: 'gene_dusp4', label: 'DUSP4', type: 'Gene', size: 30 },
    { id: 'gene_jun', label: 'JUN', type: 'Gene', size: 32 },
    { id: 'gene_etv4', label: 'ETV4', type: 'Gene', size: 30 },
    { id: 'gene_dusp5', label: 'DUSP5', type: 'Gene', size: 30 },
    { id: 'gene_rps6ka3', label: 'RPS6KA3', type: 'Gene', size: 30 },
    { id: 'gene_elk4', label: 'ELK4', type: 'Gene', size: 30 },
    { id: 'gene_ets1', label: 'ETS1', type: 'Gene', size: 30 },
    { id: 'gene_cdk4', label: 'CDK4', type: 'Gene', size: 30 },
    { id: 'gene_tert', label: 'TERT', type: 'Gene', size: 30 },
    { id: 'gene_max', label: 'MAX', type: 'Gene', size: 30 },
    { id: 'mir_34a', label: 'miR-34a', type: 'miRNA', size: 28 },
    { id: 'gene_junb', label: 'JUNB', type: 'Gene', size: 30 },
    { id: 'gene_atf3', label: 'ATF3', type: 'Gene', size: 30 },
    { id: 'gene_mmp9', label: 'MMP9', type: 'Gene', size: 30 },
    { id: 'gene_cdk6', label: 'CDK6', type: 'Gene', size: 30 },
    { id: 'gene_rb1', label: 'RB1', type: 'Gene', size: 30 },
    { id: 'drug_palbociclib', label: 'Palbociclib', type: 'Drug', size: 34 },
    { id: 'gene_egr1', label: 'EGR1', type: 'Gene', size: 30 },
    { id: 'gene_srf', label: 'SRF', type: 'Gene', size: 30 },
    { id: 'gene_fgfr1', label: 'FGFR1', type: 'Gene', size: 30 },
    { id: 'gene_spry4', label: 'SPRY4', type: 'Gene', size: 30 },
    { id: 'gene_egfr', label: 'EGFR', type: 'Gene', size: 32 },
    { id: 'gene_fgfr2', label: 'FGFR2', type: 'Gene', size: 30 },
    { id: 'gene_nfkb1', label: 'NFKB1', type: 'Gene', size: 30 },
    { id: 'gene_rela', label: 'RELA', type: 'Gene', size: 30 },
    { id: 'gene_pten', label: 'PTEN', type: 'Gene', size: 32 },
    { id: 'gene_e2f1', label: 'E2F1', type: 'Gene', size: 30 },
    { id: 'gene_bcl2l11', label: 'BCL2L11', type: 'Gene', size: 30 },
    { id: 'gene_pdcd4', label: 'PDCD4', type: 'Gene', size: 30 },
    { id: 'gene_tpm1', label: 'TPM1', type: 'Gene', size: 30 },
    { id: 'gene_braf_fusion', label: 'BRAF fusion', type: 'Gene', size: 32 },
    { id: 'gene_kiaa1549', label: 'KIAA1549', type: 'Gene', size: 30 },
    { id: 'gene_rassf1', label: 'RASSF1', type: 'Gene', size: 30 },
    { id: 'gene_cdkn2a', label: 'CDKN2A', type: 'Gene', size: 30 },
    { id: 'gene_axl', label: 'AXL', type: 'Gene', size: 30 },
    { id: 'gene_dusp1', label: 'DUSP1', type: 'Gene', size: 30 },
]

export const MOCK_EDGES: GraphEdge[] = [
    { id: 'e_1', source: 'gene_braf', target: 'gene_mek1', correlation: 0.92 },
    { id: 'e_2', source: 'gene_braf', target: 'gene_mek2', correlation: 0.83 },
    { id: 'e_3', source: 'gene_braf', target: 'gene_erk1', correlation: 0.78 },
    { id: 'e_4', source: 'gene_braf', target: 'gene_dusp6', correlation: 0.72 },
    { id: 'e_5', source: 'gene_braf', target: 'gene_fos', correlation: 0.67 },

    { id: 'e_6', source: 'gene_mek1', target: 'gene_erk1', correlation: 0.88 },
    { id: 'e_7', source: 'gene_mek1', target: 'gene_erk2', correlation: 0.79 },
    { id: 'e_8', source: 'gene_mek1', target: 'gene_elk1', correlation: 0.76 },
    { id: 'e_9', source: 'gene_mek2', target: 'gene_erk2', correlation: 0.81 },

    { id: 'e_10', source: 'gene_erk1', target: 'gene_myc', correlation: 0.81 },
    { id: 'e_11', source: 'gene_erk1', target: 'gene_fos', correlation: 0.79 },
    { id: 'e_12', source: 'gene_erk2', target: 'gene_ccnd1', correlation: 0.68 },
    { id: 'e_13', source: 'gene_elk1', target: 'gene_myc', correlation: 0.61 },
    { id: 'e_14', source: 'gene_fos', target: 'gene_ccnd1', correlation: 0.58 },

    { id: 'e_15', source: 'mir_17', target: 'gene_braf', correlation: -0.66 },
    { id: 'e_16', source: 'mir_21', target: 'gene_mek1', correlation: -0.57 },
    { id: 'e_17', source: 'cna_7q34', target: 'gene_braf', correlation: 0.73 },
    { id: 'e_18', source: 'meth_rassf1', target: 'gene_braf', correlation: -0.54 },
    { id: 'e_19', source: 'drug_vemurafenib', target: 'gene_braf', correlation: -0.89 },

    { id: 'e_20', source: 'gene_map3k8', target: 'gene_mek1', correlation: 0.55 },
    { id: 'e_21', source: 'gene_braf', target: 'gene_map3k8', correlation: 0.52 },

    { id: 'e_22', source: 'gene_spry2', target: 'gene_braf', correlation: -0.32 },
    { id: 'e_23', source: 'drug_vemurafenib', target: 'gene_mek1', correlation: -0.41 },
]

export const MOCK_EXPANSION_EDGES_BY_ROOT: Record<string, GraphEdge[]> = {
    gene_mek1: [
        { id: 'e_exp_mek1_1', source: 'gene_raf1', target: 'gene_mek1', correlation: 0.86 },
        { id: 'e_exp_mek1_2', source: 'gene_grb2', target: 'gene_mek1', correlation: 0.62 },
        { id: 'e_exp_mek1_3', source: 'gene_mek1', target: 'gene_akt1', correlation: 0.74 },
        { id: 'e_exp_mek1_4', source: 'drug_trametinib', target: 'gene_mek1', correlation: -0.91 },
        { id: 'e_exp_mek1_5', source: 'gene_akt1', target: 'gene_myc', correlation: 0.58 },
    ],
    gene_mek2: [
        { id: 'e_exp_mek2_1', source: 'gene_mek2', target: 'gene_mapkapk2', correlation: 0.73 },
        { id: 'e_exp_mek2_2', source: 'gene_mek2', target: 'gene_rps6ka1', correlation: 0.69 },
        { id: 'e_exp_mek2_3', source: 'gene_dusp4', target: 'gene_mek2', correlation: -0.61 },
    ],
    gene_erk1: [
        { id: 'e_exp_erk1_1', source: 'gene_erk1', target: 'gene_jun', correlation: 0.84 },
        { id: 'e_exp_erk1_2', source: 'gene_erk1', target: 'gene_etv4', correlation: 0.78 },
        { id: 'e_exp_erk1_3', source: 'gene_dusp5', target: 'gene_erk1', correlation: -0.71 },
        { id: 'e_exp_erk1_4', source: 'gene_jun', target: 'gene_fos', correlation: 0.65 },
    ],
    gene_erk2: [
        { id: 'e_exp_erk2_1', source: 'gene_erk2', target: 'gene_rps6ka3', correlation: 0.82 },
        { id: 'e_exp_erk2_2', source: 'gene_erk2', target: 'gene_elk4', correlation: 0.73 },
        { id: 'e_exp_erk2_3', source: 'gene_ets1', target: 'gene_erk2', correlation: 0.59 },
    ],
    gene_myc: [
        { id: 'e_exp_myc_1', source: 'gene_myc', target: 'gene_cdk4', correlation: 0.82 },
        { id: 'e_exp_myc_2', source: 'gene_myc', target: 'gene_tert', correlation: 0.76 },
        { id: 'e_exp_myc_3', source: 'gene_max', target: 'gene_myc', correlation: 0.88 },
        { id: 'e_exp_myc_4', source: 'mir_34a', target: 'gene_myc', correlation: -0.79 },
    ],
    gene_fos: [
        { id: 'e_exp_fos_1', source: 'gene_fos', target: 'gene_junb', correlation: 0.84 },
        { id: 'e_exp_fos_2', source: 'gene_fos', target: 'gene_atf3', correlation: 0.76 },
        { id: 'e_exp_fos_3', source: 'gene_junb', target: 'gene_mmp9', correlation: 0.71 },
        { id: 'e_exp_fos_4', source: 'mir_21', target: 'gene_fos', correlation: -0.62 },
    ],
    gene_ccnd1: [
        { id: 'e_exp_ccnd1_1', source: 'gene_ccnd1', target: 'gene_cdk6', correlation: 0.81 },
        { id: 'e_exp_ccnd1_2', source: 'gene_ccnd1', target: 'gene_rb1', correlation: -0.64 },
        { id: 'e_exp_ccnd1_3', source: 'drug_palbociclib', target: 'gene_ccnd1', correlation: -0.88 },
    ],
    gene_elk1: [
        { id: 'e_exp_elk1_1', source: 'gene_elk1', target: 'gene_egr1', correlation: 0.79 },
        { id: 'e_exp_elk1_2', source: 'gene_srf', target: 'gene_elk1', correlation: 0.61 },
    ],
    gene_dusp6: [
        { id: 'e_exp_dusp6_1', source: 'gene_dusp6', target: 'gene_fgfr1', correlation: -0.75 },
        { id: 'e_exp_dusp6_2', source: 'gene_dusp6', target: 'gene_spry4', correlation: 0.66 },
    ],
    gene_spry2: [
        { id: 'e_exp_spry2_1', source: 'gene_spry2', target: 'gene_egfr', correlation: -0.72 },
        { id: 'e_exp_spry2_2', source: 'gene_fgfr2', target: 'gene_spry2', correlation: 0.69 },
    ],
    gene_map3k8: [
        { id: 'e_exp_map3k8_1', source: 'gene_map3k8', target: 'gene_nfkb1', correlation: 0.8 },
        { id: 'e_exp_map3k8_2', source: 'gene_map3k8', target: 'gene_rela', correlation: 0.73 },
    ],
    mir_17: [
        { id: 'e_exp_mir17_1', source: 'mir_17', target: 'gene_pten', correlation: -0.82 },
        { id: 'e_exp_mir17_2', source: 'mir_17', target: 'gene_e2f1', correlation: -0.69 },
        { id: 'e_exp_mir17_3', source: 'gene_e2f1', target: 'gene_bcl2l11', correlation: 0.64 },
    ],
    mir_21: [
        { id: 'e_exp_mir21_1', source: 'mir_21', target: 'gene_pdcd4', correlation: -0.86 },
        { id: 'e_exp_mir21_2', source: 'mir_21', target: 'gene_pten', correlation: -0.72 },
        { id: 'e_exp_mir21_3', source: 'mir_21', target: 'gene_tpm1', correlation: -0.61 },
    ],
    cna_7q34: [
        { id: 'e_exp_cna7q34_1', source: 'cna_7q34', target: 'gene_braf_fusion', correlation: 0.93 },
        { id: 'e_exp_cna7q34_2', source: 'gene_kiaa1549', target: 'gene_braf_fusion', correlation: 0.77 },
        { id: 'e_exp_cna7q34_3', source: 'gene_braf_fusion', target: 'gene_braf', correlation: 0.84 },
    ],
    meth_rassf1: [
        { id: 'e_exp_meth_rassf1_1', source: 'meth_rassf1', target: 'gene_rassf1', correlation: -0.88 },
        { id: 'e_exp_meth_rassf1_2', source: 'gene_rassf1', target: 'gene_cdkn2a', correlation: 0.62 },
    ],
    drug_vemurafenib: [
        { id: 'e_exp_vemurafenib_1', source: 'drug_vemurafenib', target: 'gene_axl', correlation: 0.72 },
        { id: 'e_exp_vemurafenib_2', source: 'drug_vemurafenib', target: 'gene_egfr', correlation: 0.68 },
        { id: 'e_exp_vemurafenib_3', source: 'gene_dusp1', target: 'gene_braf', correlation: -0.55 },
    ],
}
