# Generated by Django 3.2.13 on 2023-04-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0003_statisticalvalidation_statisticalvalidationsourceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalvalidationsourceresult',
            name='mean_squared_error',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticalvalidation',
            name='c_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticalvalidation',
            name='log_likelihood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticalvalidation',
            name='mean_squared_error',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticalvalidation',
            name='roc_auc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
