# Generated by Django 3.2.13 on 2023-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0004_auto_20230426_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticalvalidation',
            old_name='log_likelihood',
            new_name='cox_log_likelihood',
        ),
        migrations.AddField(
            model_name='statisticalvalidation',
            name='cox_c_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
