# Generated by Django 3.2.13 on 2023-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0005_auto_20230427_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticalvalidation',
            old_name='roc_auc',
            new_name='r2_score',
        ),
    ]
