# Generated by Django 3.2.13 on 2023-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0006_rename_roc_auc_statisticalvalidation_r2_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticalvalidationsourceresult',
            old_name='log_likelihood',
            new_name='cox_log_likelihood',
        ),
        migrations.RenameField(
            model_name='statisticalvalidationsourceresult',
            old_name='roc_auc',
            new_name='r2_score',
        ),
        migrations.AddField(
            model_name='statisticalvalidationsourceresult',
            name='cox_c_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
