# Generated by Django 3.2.13 on 2023-04-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0007_auto_20230427_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeWithCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('coeff', models.FloatField()),
                ('type', models.IntegerField(choices=[(1, 'Mrna'), (2, 'Mirna'), (3, 'Cna'), (4, 'Methylation')])),
                ('statistical_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules_with_coefficients', to='statistical_properties.statisticalvalidation')),
            ],
        ),
    ]
