# Generated by Django 3.2.13 on 2023-05-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0008_moleculewithcoefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAndCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=20)),
                ('statistical_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_and_clusters', to='statistical_properties.statisticalvalidation')),
            ],
        ),
    ]
