# Generated by Django 3.2.13 on 2023-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0010_alter_statisticalvalidation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleandcluster',
            name='cluster',
            field=models.IntegerField(),
        ),
    ]
