# Generated by Django 3.2.13 on 2023-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0011_alter_sampleandcluster_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticalvalidation',
            name='state',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Finished With Error'), (3, 'In Process'), (4, 'Waiting For Queue'), (5, 'No Samples In Common'), (6, 'Stopping'), (7, 'Stopped'), (8, 'Reached Attempts Limit'), (9, 'No Features Found'), (10, 'No Valid Samples'), (11, 'No Valid Molecules')]),
        ),
    ]
