# Generated by Django 3.2.20 on 2023-09-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0015_statisticalvalidation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalvalidation',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
