# Generated by Django 4.2.19 on 2026-01-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0062_alter_experiment_clinical_source_and_more"),
        ("statistical_properties", "0017_alter_statisticalvalidation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedatastatisticalproperties",
            name="gem_normality",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_data_statistical_properties_as_gem_normality",
                to="statistical_properties.normalitytest",
            ),
        ),
        migrations.AlterField(
            model_name="sourcedatastatisticalproperties",
            name="gene_normality",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_data_statistical_properties_as_gene_normality",
                to="statistical_properties.normalitytest",
            ),
        ),
        migrations.AlterField(
            model_name="statisticalvalidationsourceresult",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistical_validation_source_results",
                to="api_service.experimentsource",
            ),
        ),
    ]
