# Generated by Django 3.2.13 on 2023-04-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_service', '0052_auto_20220923_2322'),
        ('biomarkers', '0005_auto_20230401_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.IntegerField(choices=[(1, 'Blind Search'), (2, 'Cox Regression'), (3, 'Bbha'), (4, 'Pso')])),
                ('fitness_function', models.IntegerField(choices=[(1, 'Clustering'), (2, 'Svm'), (3, 'Rf')])),
                ('execution_time', models.PositiveIntegerField(default=0)),
                ('clinical_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_clinical', to='api_service.experimentsource')),
                ('cna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_cna', to='api_service.experimentsource')),
                ('created_biomarker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fs_experiment', to='biomarkers.biomarker')),
                ('methylation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_methylation', to='api_service.experimentsource')),
                ('mirna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_mirna', to='api_service.experimentsource')),
                ('mrna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_mrna', to='api_service.experimentsource')),
                ('origin_biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_origin', to='biomarkers.biomarker')),
            ],
        ),
        migrations.CreateModel(
            name='SVMParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.IntegerField(choices=[(1, 'Linear'), (2, 'Polynomial'), (3, 'Rbf')])),
                ('task', models.IntegerField(choices=[(1, 'Ranking'), (2, 'Regression')])),
                ('experiment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svm_parameters', to='feature_selection.fsexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='ClusteringParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.IntegerField(choices=[(1, 'K Means')])),
                ('metric', models.IntegerField(choices=[(1, 'Cox Regression'), (2, 'Log Rank Test')])),
                ('experiment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustering_parameters', to='feature_selection.fsexperiment')),
            ],
        ),
    ]
