# Generated by Django 3.2.13 on 2023-04-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0052_auto_20220923_2322'),
        ('feature_selection', '0002_fsexperiment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsexperiment',
            name='clinical_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_experiments_as_clinical', to='api_service.experimentclinicalsource'),
        ),
    ]
