# Generated by Django 3.2.13 on 2023-04-17 18:47

from django.db import migrations, models
import django.db.models.deletion
import feature_selection.models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0006_alter_biomarker_state'),
        ('feature_selection', '0003_alter_fsexperiment_clinical_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_dump', models.FileField(upload_to=feature_selection.models.user_directory_path_for_trained_models)),
                ('best_fitness_value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='biomarkers.biomarker')),
                ('fs_experiment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_model', to='feature_selection.fsexperiment')),
            ],
        ),
    ]
