# Generated by Django 3.2.13 on 2023-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0004_trainedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringparameters',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral')]),
        ),
    ]
