# Generated by Django 3.2.13 on 2023-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0005_alter_clusteringparameters_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringparameters',
            name='scoring_method',
            field=models.IntegerField(choices=[(1, 'C Index'), (2, 'Log Likelihood')], default=1),
        ),
        migrations.AlterField(
            model_name='clusteringparameters',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral')], default=1),
        ),
        migrations.AlterField(
            model_name='clusteringparameters',
            name='metric',
            field=models.IntegerField(choices=[(1, 'Cox Regression'), (2, 'Log Rank Test')], default=1),
        ),
    ]
