# Generated by Django 3.2.13 on 2023-05-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0052_auto_20220923_2322'),
        ('feature_selection', '0010_trainedmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='clinical_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models_as_clinical', to='api_service.experimentclinicalsource'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='cna_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models_as_cna', to='api_service.experimentsource'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='methylation_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models_as_methylation', to='api_service.experimentsource'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mirna_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models_as_mirna', to='api_service.experimentsource'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='mrna_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_models_as_mrna', to='api_service.experimentsource'),
        ),
    ]
