# Generated by Django 3.2.13 on 2023-05-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets_synchronization', '0029_auto_20220923_2322'),
        ('feature_selection', '0011_auto_20230508_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='survival_column_tuple_cgds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='datasets_synchronization.survivalcolumnstuplecgdsdataset'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='survival_column_tuple_user_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='datasets_synchronization.survivalcolumnstupleuserfile'),
        ),
    ]
