# Generated by Django 3.2.13 on 2023-05-10 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0013_auto_20230508_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringparameters',
            name='n_clusters',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='svmparameters',
            name='max_iterations',
            field=models.SmallIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.CreateModel(
            name='RFParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_estimators', models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)])),
                ('max_depth', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3)])),
                ('random_state', models.SmallIntegerField(blank=True, null=True)),
                ('trained_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_parameters', to='feature_selection.trainedmodel')),
            ],
        ),
    ]
