# Generated by Django 3.2.13 on 2023-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0014_auto_20230510_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='state',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Finished With Error'), (3, 'In Process'), (4, 'Waiting For Queue'), (5, 'No Samples In Common'), (6, 'Stopping'), (7, 'Stopped'), (8, 'Reached Attempts Limit'), (9, 'No Features Found')]),
        ),
    ]
