# Generated by Django 3.2.13 on 2023-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0018_auto_20230522_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterlabel',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
