# Generated by Django 3.2.13 on 2023-05-23 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0020_alter_clusterlabel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRangeLabelsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_ranges_labels', to='feature_selection.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRangeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=9, null=True)),
                ('min_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.FloatField()),
                ('cluster_label_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='feature_selection.predictionrangelabelsset')),
            ],
        ),
    ]
