# Generated by Django 3.2.13 on 2023-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0022_rename_cluster_label_set_predictionrangelabel_prediction_range_label_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrangelabel',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
