# Generated by Django 3.2.13 on 2023-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0024_rename_prediction_range_label_set_predictionrangelabel_prediction_range_labels_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsexperiment',
            name='emr_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
