# Generated by Django 3.2.13 on 2023-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0025_fsexperiment_emr_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsexperiment',
            name='clinical_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fsexperiment',
            name='molecules_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
