# Generated by Django 3.2.13 on 2023-06-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0026_auto_20230608_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoxRegressionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_n', models.PositiveSmallIntegerField()),
                ('fs_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feature_selection.fsexperiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BBHAParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_stars', models.PositiveSmallIntegerField()),
                ('n_iterations', models.PositiveSmallIntegerField()),
                ('version_used', models.IntegerField(choices=[(1, 'Original'), (2, 'Improved')])),
                ('fs_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feature_selection.fsexperiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
