# Generated by Django 3.2.13 on 2023-06-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0027_bbhaparameters_coxregressionparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsexperiment',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
