# Generated by Django 3.2.13 on 2023-06-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0029_clusteringtimesrecord_rftimesrecord_svmtimesrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteringtimesrecord',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='rftimesrecord',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='svmtimesrecord',
            name='parameters',
        ),
    ]
