# Generated by Django 3.2.13 on 2023-06-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0030_auto_20230614_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsexperiment',
            name='clinical_path',
        ),
        migrations.RemoveField(
            model_name='fsexperiment',
            name='molecules_path',
        ),
    ]
