# Generated by Django 3.2.13 on 2023-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0032_alter_trainedmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringparameters',
            name='penalizer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
