# Generated by Django 3.2.13 on 2023-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0034_alter_trainedmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringparameters',
            name='penalizer',
            field=models.FloatField(default=0.0),
        ),
    ]
