# Generated by Django 3.2.13 on 2023-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0037_auto_20230629_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringtimesrecord',
            name='scoring_method',
            field=models.IntegerField(choices=[(1, 'C Index'), (2, 'Log Likelihood')], default=0),
            preserve_default=False,
        ),
    ]
