# Generated by Django 3.2.13 on 2023-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0038_clusteringtimesrecord_scoring_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='execution_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='test_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rftimesrecord',
            name='execution_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rftimesrecord',
            name='test_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='execution_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='test_time',
            field=models.FloatField(),
        ),
    ]
