# Generated by Django 3.2.13 on 2023-06-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0039_auto_20230629_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusteringtimesrecord',
            name='test_time',
        ),
    ]
