# Generated by Django 3.2.13 on 2023-07-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0040_remove_clusteringtimesrecord_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='number_of_clusters',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='number_of_features',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='number_of_samples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rftimesrecord',
            name='number_of_features',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rftimesrecord',
            name='number_of_samples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rftimesrecord',
            name='number_of_trees',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='max_iterations',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='number_of_features',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='number_of_iterations',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='number_of_samples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='time_by_iteration',
            field=models.IntegerField(),
        ),
    ]
