# Generated by Django 3.2.13 on 2023-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0041_auto_20230704_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmtimesrecord',
            name='time_by_iteration',
            field=models.FloatField(),
        ),
    ]
