# Generated by Django 3.2.13 on 2023-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0043_alter_trainedmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='cross_validation_folds',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
