# Generated by Django 3.2.13 on 2023-07-12 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0044_trainedmodel_cross_validation_folds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='cross_validation_folds',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
