# Generated by Django 3.2.13 on 2023-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0045_alter_trainedmodel_cross_validation_folds'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='cv_folds_modified',
            field=models.BooleanField(default=False),
        ),
    ]
