# Generated by Django 3.2.13 on 2023-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0046_trainedmodel_cv_folds_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
