# Generated by Django 3.2.20 on 2023-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0049_fsexperiment_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
