# Generated by Django 3.2.20 on 2023-12-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0051_alter_trainedmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsexperiment',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'Blind Search'), (2, 'Cox Regression'), (3, 'Bbha'), (4, 'Pso'), (5, 'Ga')]),
        ),
        migrations.CreateModel(
            name='GeneticAlgorithmsParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_iterations', models.PositiveSmallIntegerField()),
                ('population_size', models.PositiveSmallIntegerField(default=50)),
                ('mutation_rate', models.FloatField(default=0.01)),
                ('fs_experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feature_selection.fsexperiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
