# Generated by Django 4.2.15 on 2024-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0054_alter_trainedmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsexperiment',
            name='app_name',
            field=models.CharField(blank=True, help_text='Spark app name to get the results', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of attempts to prevent a buggy experiment running forever'),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='emr_job_id',
            field=models.CharField(blank=True, help_text='Job ID in the Spark cluster', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='execution_time',
            field=models.PositiveIntegerField(default=0, help_text='Execution time in seconds'),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery Task ID', max_length=100, null=True),
        ),
    ]
