# Generated by Django 4.2.15 on 2024-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0055_alter_fsexperiment_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringparameters',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means')], default=1),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means')]),
        ),
    ]
