# Generated by Django 4.2.15 on 2024-11-07 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0056_alter_clusteringparameters_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringparameters',
            name='eps',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='clusteringparameters',
            name='min_samples',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='clusteringparameters',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means'), (4, 'Dbscan')], default=1),
        ),
        migrations.AlterField(
            model_name='clusteringparameters',
            name='n_clusters',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='clusteringparameters',
            name='penalizer',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means'), (4, 'Dbscan')]),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='emr_job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='execution_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fsexperiment',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
