# Generated by Django 4.2.15 on 2025-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0056_alter_clusteringparameters_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringparameters',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means'), (4, 'Ward')], default=1),
        ),
        migrations.AlterField(
            model_name='clusteringtimesrecord',
            name='algorithm',
            field=models.IntegerField(choices=[(1, 'K Means'), (2, 'Spectral'), (3, 'Bk Means'), (4, 'Ward')]),
        ),
    ]
