# Generated by Django 3.0.3 on 2020-06-09 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_auto_20200512_1925'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('file_obj', models.FileField(upload_to=user_files.models.user_directory_path)),
                ('file_type', models.IntegerField(choices=[(1, 'Mrna'), (2, 'Mirna'), (3, 'Cna'), (4, 'Methylation'), (5, 'Clinical')])),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('institutions', models.ManyToManyField(blank=True, to='institutions.Institution')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
