# Generated by Django 3.0.3 on 2020-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0002_auto_20200819_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='number_of_rows',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='number_of_samples',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        )
    ]
