# Generated by Django 3.0.3 on 2020-08-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0003_auto_20200827_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='number_of_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='number_of_samples',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
