# Generated by Django 3.0.3 on 2020-09-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0006_auto_20200831_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_cpg_site_id',
            field=models.BooleanField(default=False),
        ),
    ]
