# Generated by Django 3.0.3 on 2020-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0009_userfile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='platform',
            field=models.IntegerField(blank=True, choices=[(450, 'Platform 450')], null=True),
        ),
    ]
