# Generated by Django 3.0.3 on 2020-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0010_auto_20200903_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='decimal_separator',
            field=models.CharField(choices=[('.', 'Dot'), (',', 'Comma')], default='.', max_length=1),
        ),
    ]
