# Generated by Django 3.1.2 on 2021-03-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0011_userfile_decimal_separator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
