# Generated by Django 3.2.13 on 2022-09-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0012_userfile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
