# Generated by Django 3.2.13 on 2022-09-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0013_alter_userfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
