# Generated by Django 3.2.13 on 2023-01-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0014_alter_userfile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'ordering': ['-id']},
        ),
    ]
