# Generated by Django 4.2.19 on 2026-02-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tissues", "0001_initial"),
        ("user_files", "0015_alter_userfile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="tissue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tissues.tissue",
            ),
        ),
    ]
