# Generated by Django 4.2.19 on 2026-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tissues", "0002_tissue_code_and_initial_data"),
        ("user_files", "0016_userfile_tissue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="tissue",
        ),
        migrations.AddField(
            model_name="userfile",
            name="tissues",
            field=models.ManyToManyField(blank=True, to="tissues.tissue"),
        ),
    ]
