# Generated by Django 4.2.19 on 2026-06-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tissues", "0002_tissue_code_and_initial_data"),
        ("user_files", "0017_remove_userfile_tissue_userfile_tissues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="tissues",
        ),
        migrations.AddField(
            model_name="userfile",
            name="tissues",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tissues.tissue",
            ),
        ),
    ]
