# Generated by Django 4.2.19 on 2026-07-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_files", "0018_remove_userfile_tissues_userfile_tissues"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfile",
            old_name="tissues",
            new_name="tissue",
        ),
    ]
