# Generated by Django 3.1.2 on 2021-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('chromosome', models.CharField(max_length=30)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
            ],
        ),
    ]
