# Generated by Django 3.1.2 on 2021-01-14 23:31

from django.db import migrations
import pandas as pd
import os.path
import pathlib


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Gene = apps.get_model("genes", "Gene")
    db_alias = schema_editor.connection.alias

    # Imports all the genes info
    current_file_path = pathlib.Path(__file__).parent.absolute()
    gene_data_path = os.path.join(current_file_path, 'Ensemble_GRCh37.p13_for_multiomics.tar.gz')
    genes_df: pd.DataFrame = pd.read_json(gene_data_path)
    genes_to_insert = [
        Gene(
            name=elem.name,
            type=elem.type,
            description=elem.description,
            chromosome=elem.chromosome,
            start=elem.start,
            end=elem.end,
        )
        for elem in genes_df.itertuples()
    ]
    Gene.objects.using(db_alias).bulk_create(genes_to_insert)


def reverse_func(apps, schema_editor):
    # reverse_func() deletes created data
    Gene = apps.get_model("genes", "Gene")
    db_alias = schema_editor.connection.alias
    Gene.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
