"""Shared visibility rules for resources exposed through the API.

The application has several resource models with the same visibility contract:
the owner can access the resource, public resources are visible to every
authenticated user, and resources can be shared with users or institutions.
Keeping the predicates here avoids individual endpoints drifting apart.
"""

from typing import Any

from django.contrib.auth.base_user import AbstractBaseUser
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q


def shared_resource_visibility_q(user: AbstractBaseUser) -> Q:
    """Return the direct visibility predicate for a shareable resource."""
    return (
        Q(user=user)
        | Q(is_public=True)
        | Q(shared_users=user)
        | Q(shared_institutions__users=user)
    )


def can_view_shared_resource(resource: Any, user: AbstractBaseUser) -> bool:
    """Check direct visibility for Experiment-like resources."""
    if not user or not user.is_authenticated:
        return False

    return (
        resource.user_id == user.id
        or resource.is_public
        or resource.shared_users.filter(pk=user.pk).exists()
        or resource.shared_institutions.filter(users=user).exists()
    )


def biomarker_visibility_q(user: AbstractBaseUser) -> Q:
    """Return visibility for a biomarker and FS-generated biomarker.

    A biomarker generated by feature selection is a derived resource. Its
    origin biomarker is therefore also a source of visibility.
    """
    direct = shared_resource_visibility_q(user)
    origin = (
        Q(fs_experiment__origin_biomarker__user=user)
        | Q(fs_experiment__origin_biomarker__is_public=True)
        | Q(fs_experiment__origin_biomarker__shared_users=user)
        | Q(fs_experiment__origin_biomarker__shared_institutions__users=user)
    )
    return direct | origin


def can_view_biomarker(biomarker: Any, user: AbstractBaseUser) -> bool:
    """Check direct or inherited visibility for a biomarker."""
    if can_view_shared_resource(biomarker, user):
        return True

    try:
        origin_biomarker = biomarker.fs_experiment.origin_biomarker
    except ObjectDoesNotExist:
        return False

    return can_view_shared_resource(origin_biomarker, user)


def can_edit_shared_resource(resource: Any, user: AbstractBaseUser) -> bool:
    """Only the owner may mutate sharing or resource content."""
    return bool(user and user.is_authenticated and resource.user_id == user.id)


def can_view_user_file(user_file: Any, user: AbstractBaseUser) -> bool:
    """Visibility supported by the current UserFile model.

    UserFile currently supports owner, public, and institution visibility. It
    intentionally does not include per-user sharing.
    """
    if not user or not user.is_authenticated:
        return False

    return (
        user_file.user_id == user.id
        or user_file.is_public
        or user_file.institutions.filter(users=user).exists()
    )


def user_file_visibility_q(user: AbstractBaseUser) -> Q:
    """Return visibility supported by the current UserFile model."""
    return Q(user=user) | Q(is_public=True) | Q(institutions__users=user)


def can_edit_user_file(user_file: Any, user: AbstractBaseUser) -> bool:
    """Return whether the user may edit/delete a UserFile."""
    if not user or not user.is_authenticated:
        return False

    return (
        user_file.user_id == user.id
        or user_file.institutions.filter(
            users=user,
            institutionadministration__is_institution_admin=True,
        ).exists()
    )
