# Generated by Django 3.2.13 on 2023-05-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_service', '0052_auto_20220923_2322'),
        ('biomarkers', '0013_alter_biomarker_state'),
        ('feature_selection', '0017_clusterlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Completed'), (2, 'Finished With Error'), (3, 'In Process'), (4, 'Waiting For Queue'), (5, 'No Samples In Common'), (6, 'Stopping'), (7, 'Stopped'), (8, 'Reached Attempts Limit'), (9, 'No Features Found')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments', to='biomarkers.biomarker')),
                ('cna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments_as_cna', to='api_service.experimentsource')),
                ('methylation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments_as_methylation', to='api_service.experimentsource')),
                ('mirna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments_as_mirna', to='api_service.experimentsource')),
                ('mrna_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments_as_mrna', to='api_service.experimentsource')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='feature_selection.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SampleAndClusterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=20)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_and_clusters', to='inferences.inferenceexperiment')),
            ],
        ),
    ]
