# Generated by Django 3.2.13 on 2023-05-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_selection', '0017_clusterlabel'),
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleandclusterprediction',
            old_name='prediction',
            new_name='experiment',
        ),
        migrations.AlterField(
            model_name='inferenceexperiment',
            name='trained_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_experiments', to='feature_selection.trainedmodel'),
        ),
    ]
