# Generated by Django 3.2.13 on 2023-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0002_auto_20230516_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleandclusterprediction',
            name='cluster',
            field=models.IntegerField(),
        ),
    ]
