# Generated by Django 3.2.13 on 2023-05-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0052_auto_20220923_2322'),
        ('inferences', '0004_sampleandtimeprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceexperiment',
            name='clinical_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_experiments', to='api_service.experimentclinicalsource'),
        ),
    ]
