# Generated by Django 3.2.20 on 2023-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0008_alter_inferenceexperiment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceexperiment',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inferenceexperiment',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
