# Generated by Django 3.0.1 on 2020-02-27 19:07

import api_service.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import user_files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets_synchronization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgds_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets_synchronization.CGDSDataset')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.IntegerField(choices=[(1, 'File'), (2, 'Experiment')])),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('file_obj', models.FileField(upload_to=user_files.models.user_directory_path)),
                ('file_type', models.IntegerField(choices=[(1, 'Mrna'), (2, 'Mirna'), (3, 'Cnv'), (4, 'Methylation'), (5, 'Follow Up')])),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_service.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MrnaMirnaExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('minimum_coefficient_threshold', models.FloatField(default=0.7)),
                ('state', models.IntegerField(choices=[(1, 'Waiting For Queue'), (2, 'In Process'), (3, 'Completed'), (4, 'Finished With Error')])),
                ('result_unique_key', models.CharField(blank=True, max_length=18, null=True)),
                ('result_total_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('result_final_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('follow_up_file', models.FileField(upload_to=user_files.models.user_directory_path)),
                ('keep_mirna_interaction', models.BooleanField()),
                ('mRNA_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrna_source', to='api_service.ExperimentSource')),
                ('miRNA_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.ExperimentSource')),
                ('tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_service.Tag')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experimentsource',
            name='user_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.UserFile'),
        ),
    ]
