# Generated by Django 3.0.3 on 2020-03-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrnamirnaexperiment',
            name='correlation_method',
            field=models.IntegerField(choices=[(1, 'Spearman'), (2, 'Kendall'), (3, 'Pearson')], default=1),
            preserve_default=False,
        ),
    ]
