# Generated by Django 3.0.3 on 2020-03-30 14:31

import api_service.models
from django.db import migrations, models

import user_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0004_mrnamirnaexperiment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnamirnaexperiment',
            name='follow_up_file',
            field=models.FileField(blank=True, null=True, upload_to=user_files.models.user_directory_path),
        ),
    ]
