# Generated by Django 3.0.3 on 2020-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0006_mrnamirnaexperiment_minimum_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrnamirnaexperiment',
            name='minimum_std',
        ),
        migrations.AddField(
            model_name='mrnamirnaexperiment',
            name='minimum_std_gem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mrnamirnaexperiment',
            name='minimum_std_gene',
            field=models.FloatField(default=0.0),
        ),
    ]
