# Generated by Django 3.0.3 on 2020-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0007_auto_20200331_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnamirnaexperiment',
            name='minimum_std_gem',
            field=models.FloatField(default=0.2),
        ),
    ]
