# Generated by Django 3.0.3 on 2020-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0009_remove_mrnamirnaexperiment_keep_mirna_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Mrna'), (2, 'Mirna'), (3, 'Cnv'), (4, 'Methylation'), (5, 'Clinical')]),
        ),
    ]
