# Generated by Django 3.0.3 on 2020-04-29 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_service', '0010_auto_20200421_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('minimum_coefficient_threshold', models.FloatField(default=0.7)),
                ('minimum_std_gene', models.FloatField(default=0.0)),
                ('minimum_std_gem', models.FloatField(default=0.2)),
                ('state', models.IntegerField(choices=[(1, 'Waiting For Queue'), (2, 'In Process'), (3, 'Completed'), (4, 'Finished With Error')])),
                ('correlation_method', models.IntegerField(choices=[(1, 'Spearman'), (2, 'Kendall'), (3, 'Pearson')])),
                ('result_unique_key', models.CharField(blank=True, max_length=18, null=True)),
                ('result_total_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('result_final_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Mirna'), (2, 'Cnv'), (3, 'Methylation')])),
                ('gem_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.ExperimentSource')),
                ('mRNA_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrna_source', to='api_service.ExperimentSource')),
                ('tag', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_service.Tag')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MrnaMirnaExperiment',
        ),
    ]
