# Generated by Django 3.0.3 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0011_auto_20200429_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mirna'), (2, 'Cna'), (3, 'Methylation')]),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Mrna'), (2, 'Mirna'), (3, 'Cna'), (4, 'Methylation'), (5, 'Clinical')]),
        ),
    ]
