# Generated by Django 3.0.3 on 2020-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20200512_1925'),
        ('api_service', '0012_auto_20200429_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='institutions',
            field=models.ManyToManyField(to='institutions.Institution'),
        ),
    ]
