# Generated by Django 3.0.3 on 2020-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20200512_1925'),
        ('api_service', '0013_userfile_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='institutions.Institution'),
        ),
    ]
