# Generated by Django 3.0.3 on 2020-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0014_auto_20200514_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting For Queue'), (2, 'In Process'), (3, 'Completed'), (4, 'Finished With Error'), (5, 'No Samples In Common')]),
        ),
    ]
