# Generated by Django 3.0.3 on 2020-06-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('api_service', '0015_auto_20200515_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.Tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
