# Generated by Django 3.0.3 on 2020-06-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0016_auto_20200609_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
    ]
