# Generated by Django 3.0.3 on 2020-06-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_files', '0001_initial'),
        ('api_service', '0017_auto_20200609_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentsource',
            name='user_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_files.UserFile'),
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
