# Generated by Django 3.0.3 on 2020-07-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0018_auto_20200609_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneMiRNACombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=15)),
                ('gem', models.CharField(max_length=30)),
                ('correlation', models.FloatField()),
                ('p_value', models.FloatField()),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.Experiment')),
            ],
            options={
                'db_table': 'gene_mirna_combination',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneMethylationCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=15)),
                ('gem', models.CharField(max_length=30)),
                ('correlation', models.FloatField()),
                ('p_value', models.FloatField()),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.Experiment')),
            ],
            options={
                'db_table': 'gene_methylation_combination',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneCNACombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=15)),
                ('gem', models.CharField(max_length=30)),
                ('correlation', models.FloatField()),
                ('p_value', models.FloatField()),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_service.Experiment')),
            ],
            options={
                'db_table': 'gene_cna_combination',
                'abstract': False,
            },
        ),
    ]
