# Generated by Django 3.0.3 on 2020-08-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0021_experiment_p_values_adjustment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataStatisticalProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genecnacombination',
            name='properties',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.SourceDataStatisticalProperties'),
        ),
        migrations.AddField(
            model_name='genemethylationcombination',
            name='properties',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.SourceDataStatisticalProperties'),
        ),
        migrations.AddField(
            model_name='genemirnacombination',
            name='properties',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.SourceDataStatisticalProperties'),
        ),
    ]
