# Generated by Django 3.0.3 on 2020-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0022_auto_20200807_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedatastatisticalproperties',
            old_name='standard_deviation',
            new_name='gene_standard_deviation',
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='gem_standard_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
