# Generated by Django 3.0.3 on 2020-08-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0023_auto_20200807_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.FloatField()),
                ('p_value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='sourcedatastatisticalproperties',
            name='gem_standard_deviation',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcedatastatisticalproperties',
            name='gene_standard_deviation',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='gem_normality',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gem_normality', to='api_service.NormalityTest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='gene_normality',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gene_normality', to='api_service.NormalityTest'),
            preserve_default=False,
        ),
    ]
