# Generated by Django 3.0.3 on 2020-08-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0024_auto_20200807_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreuschPaganTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagrange_multiplier', models.FloatField()),
                ('p_value', models.FloatField()),
                ('f_value', models.FloatField()),
                ('f_p_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GoldfeldQuandtTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.FloatField()),
                ('p_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='homoscedasticity_breusch_pagan',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_service.BreuschPaganTest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='homoscedasticity_goldfeld_quandt',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_service.GoldfeldQuandtTest'),
            preserve_default=False,
        ),
    ]
