# Generated by Django 3.0.3 on 2020-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0027_experiment_evaluated_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsource',
            name='number_of_rows',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentsource',
            name='number_of_samples',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
