# Generated by Django 3.0.3 on 2020-08-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0028_auto_20200827_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentsource',
            name='number_of_rows',
        ),
        migrations.RemoveField(
            model_name='experimentsource',
            name='number_of_samples',
        )
    ]
