# Generated by Django 3.0.3 on 2020-09-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0030_experiment_correlate_with_all_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='gem_mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='gene_mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
