# Generated by Django 3.0.3 on 2020-10-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0032_sourcedatastatisticalproperties_number_of_samples_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataOutliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_identifier', models.CharField(max_length=100)),
                ('expression', models.FloatField()),
                ('stats_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outliers', to='api_service.SourceDataStatisticalProperties')),
            ],
        ),
    ]
