# Generated by Django 3.0.3 on 2020-10-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0033_sourcedataoutliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedataoutliers',
            name='is_gene_data',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
