# Generated by Django 3.0.3 on 2020-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0034_sourcedataoutliers_is_gene_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecnacombination',
            name='gene',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='gene',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='gene',
            field=models.CharField(max_length=30),
        ),
    ]
