# Generated by Django 3.0.3 on 2020-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0035_auto_20201005_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecnacombination',
            name='gem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genecnacombination',
            name='gene',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='gem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='gene',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='gem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='gene',
            field=models.CharField(max_length=50),
        ),
    ]
