# Generated by Django 3.0.3 on 2020-10-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0036_auto_20201005_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.FloatField()),
                ('p_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='linearity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.LinearityTest'),
        ),
    ]
