# Generated by Django 3.0.3 on 2020-10-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0037_auto_20201005_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcedatastatisticalproperties',
            old_name='homoscedasticity_breusch_pagan',
            new_name='heteroscedasticity_breusch_pagan',
        ),
    ]
