# Generated by Django 3.0.3 on 2020-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0038_auto_20201006_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonotonicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.FloatField()),
                ('p_value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
