# Generated by Django 3.0.3 on 2020-10-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0039_monotonictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedatastatisticalproperties',
            name='monotonicity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_service.MonotonicTest'),
        ),
    ]
