# Generated by Django 3.0.3 on 2020-10-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistical_properties', '0001_initial'),
        ('api_service', '0040_sourcedatastatisticalproperties_monotonicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecnacombination',
            name='source_statistical_data',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistical_properties.SourceDataStatisticalProperties'),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='source_statistical_data',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistical_properties.SourceDataStatisticalProperties'),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='source_statistical_data',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistical_properties.SourceDataStatisticalProperties'),
        ),
    ]
