# Generated by Django 3.0.3 on 2020-10-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0041_auto_20201007_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedataoutliers',
            name='stats_property',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='gem_normality',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='gene_normality',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='heteroscedasticity_breusch_pagan',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='homoscedasticity_goldfeld_quandt',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='linearity',
        ),
        migrations.RemoveField(
            model_name='sourcedatastatisticalproperties',
            name='monotonicity',
        ),
        migrations.DeleteModel(
            name='BreuschPaganTest',
        ),
        migrations.DeleteModel(
            name='GoldfeldQuandtTest',
        ),
        migrations.DeleteModel(
            name='LinearityTest',
        ),
        migrations.DeleteModel(
            name='MonotonicTest',
        ),
        migrations.DeleteModel(
            name='NormalityTest',
        ),
        migrations.DeleteModel(
            name='SourceDataOutliers',
        ),
        migrations.DeleteModel(
            name='SourceDataStatisticalProperties',
        ),
    ]
