# Generated by Django 3.1.2 on 2020-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0042_auto_20201007_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecnacombination',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
