# Generated by Django 3.1.2 on 2021-01-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0002_auto_20210114_2331'),
        ('api_service', '0044_auto_20210115_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecnacombination',
            name='gene',
            field=models.ForeignKey(db_column='gene', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='genes.gene'),
        ),
        migrations.AlterField(
            model_name='genemethylationcombination',
            name='gene',
            field=models.ForeignKey(db_column='gene', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='genes.gene'),
        ),
        migrations.AlterField(
            model_name='genemirnacombination',
            name='gene',
            field=models.ForeignKey(db_column='gene', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='genes.gene'),
        ),
    ]
