# Generated by Django 3.1.2 on 2021-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0047_auto_20210329_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting For Queue'), (2, 'In Process'), (3, 'Completed'), (4, 'Finished With Error'), (5, 'No Samples In Common'), (6, 'Stopped')]),
        ),
    ]
