# Generated by Django 3.1.2 on 2022-05-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0050_experiment_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting For Queue'), (2, 'In Process'), (3, 'Completed'), (4, 'Finished With Error'), (5, 'No Samples In Common'), (6, 'Stopping'), (7, 'Stopped'), (8, 'Reached Attempts Limit')]),
        ),
    ]
