name: PR pipeline to verify tests and code rules
on: [pull_request]
jobs:
  Node-checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm --prefix src/frontend/static/frontend i
    - name: NPM linter checks
      run: npm --prefix src/frontend/static/frontend run check-all        
